// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------

namespace ColorTabs2019
{
    internal sealed partial class Vsix
    {
        public const string Id = "ColorTabs2019.25f93d89-e99f-4dc7-bbfc-fe37aaaad86e";
        public const string Name = "ColorTabs2019";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "HP Inc.";
        public const string Tags = "";
    }
}
