// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ColorTabs2019
{
    internal sealed partial class Vsix
    {
        public const string Id = "ColorTabs2019.25f93d89-e99f-4dc7-bbfc-fe37aaaad86e";
        public const string Name = "Color Tabs 2019";
        public const string Description = @"Color Tabs Extension for Visual Studio 2019.";
        public const string Language = "en-US";
        public const string Version = "1.4";
        public const string Author = "lsoft";
        public const string Tags = "";
    }
}
